---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: playtech/centos7

suites:
  - name: default
    run_list:
      - recipe[custom-jenkins::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      jenkins:
        master: 
          install_method: 'package'
          port: '8080'
      java:
        jdk_version: '8'
        install_flavour: 'oracle'
        accept_oracle_download_terms: true
